"""Generic large neighborhood search framework with OptDSL adapter."""

from .components import (
    AcceptanceCriterion,
    DestroyOperator,
    Evaluator,
    Initializer,
    LNSLogger,
    NeighborhoodSelector,
    RepairOperator,
    StopCriterion,
)
from .defaults import (
    ImprovingAcceptance,
    MaxIterationsStop,
    NeighborhoodPoolSelector,
    RandomFractionDestroy,
    RandomRepair,
    SampledRepair,
    SimulatedAnnealingAcceptance,
    StdoutLNSLogger,
    VariableBlockDestroy,
)
from .engine import LargeNeighborhoodSearchEngine
from .models import LNSContext, LNSResult, LNSSolution, LNSState, LNSStats
from .lns import (
    GreedyRandomizedInitializer,
    OptDSLEvaluator,
    RandomAssignmentInitializer,
    build_lns_context,
    read_problem_for_lns,
)
from .problems import CVRPRouteInitializer, detect_cvrp_problem, prepare_cvrp_assignment_for_evaluation
from .problem_reader import (
    ConstraintSpec,
    DecisionIndexSpec,
    IntDomain,
    ProblemDefinition,
    ProblemObjective,
    VariableDomain,
    VariableSpec,
    infer_assignment_variable_name,
    read_problem,
    read_problem_from_code,
)

__all__ = [
    "AcceptanceCriterion",
    "ConstraintSpec",
    "CVRPRouteInitializer",
    "DecisionIndexSpec",
    "DestroyOperator",
    "detect_cvrp_problem",
    "prepare_cvrp_assignment_for_evaluation",
    "Evaluator",
    "GreedyRandomizedInitializer",
    "ImprovingAcceptance",
    "IntDomain",
    "Initializer",
    "LargeNeighborhoodSearchEngine",
    "LNSContext",
    "LNSLogger",
    "LNSResult",
    "LNSSolution",
    "LNSState",
    "LNSStats",
    "MaxIterationsStop",
    "NeighborhoodPoolSelector",
    "NeighborhoodSelector",
    "OptDSLEvaluator",
    "ProblemDefinition",
    "ProblemObjective",
    "RandomAssignmentInitializer",
    "RandomFractionDestroy",
    "RandomRepair",
    "SampledRepair",
    "RepairOperator",
    "SimulatedAnnealingAcceptance",
    "StdoutLNSLogger",
    "StopCriterion",
    "VariableBlockDestroy",
    "VariableDomain",
    "VariableSpec",
    "build_lns_context",
    "infer_assignment_variable_name",
    "read_problem",
    "read_problem_from_code",
    "read_problem_for_lns",
]
