---
title: "Original Solution Concept"
filters:
  - pseudocode
format:
    html:
        include-in-header:
            text: |
              <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
        page-layout: full
---

# Introduction

There are two search algorithms (both tree based):
1. Layer Optimization - for a given board sequence this algorithm calculates the best cutting and stacking solution
2. Board Resorting - for a given input board sequence it simulates the resorting actions (up to a certain depth) and calls the `Layer Optimization` for the board sequence

```{mermaid}
sequenceDiagram
participant BoardResorting
participant LayerOptimization
Note left of BoardResorting: Generates a feasible board sequence for boards
Note right of LayerOptimization: Calculates the best operation sequence for a given board sequence
BoardResorting->>+LayerOptimization: Board sequence 1
LayerOptimization->>-BoardResorting: Best quality and operation sequence for board sequence 1

BoardResorting->>+LayerOptimization: Board sequence 2
LayerOptimization->>-BoardResorting: Best quality and operation sequence for board sequence 2

BoardResorting->>+LayerOptimization: ...
LayerOptimization->>-BoardResorting: ...

```

# Layer Optimization

This algorithm optimizes the cutting of the boards and uses the buffer after the saw.

The main concept of the algorithm is to generate a search tree.
A node represents the state of the machine and the current quality of the solution up to that node (i.e. scrap of good wood), depending on the state of the machine, different actions are possible.

The following example shows parts of the tree based on `two_beams_02_bad_faults.json` problem instance.

The notation 1.1 refers to the board with id 1 and part with id 1, 5.6 refers to the board with id 5 and part with id 6.

```{mermaid}
flowchart TB
t0("`inputboards=[4.4, 5.5, 5.6, 5.7, 6.8, 6.9, 6.10]
current_layer=[]
buffer=[]
scrap=0
`")

t1("`inputboards=[5.5, 5.6, 5.7, 6.8, 6.9, 6.10]
current_layer=[4.4]
buffer=[]
scrap=5
`")

t2["`inputboards=[5.5, 5.6, 5.7, 6.8, 6.9, 6.10]
current_layer=[]
buffer=[4.4]
scrap=0
`"]

t3["`invalid
`"]

t0 -->|add to layer| t1
t0 -->|put into buffer| t2
t0 -. take from buffer .-> t3


t1-1("`inputboards=[5.6, 5.7, 6.8, 6.9, 6.10]
current_layer=[4.4, 5.5]
buffer=[]
scrap=8
`")

t1-2["`inputboards=[5.6, 5.7, 6.8, 6.9, 6.10]
current_layer=[4.4]
buffer=[5.5]
scrap=5
`"]

t1-3["`invalid
`"]


t1 -->|add to layer| t1-1
t1 -->|put into buffer| t1-2
t1 -->|take from buffer| t1-3

t2-1("`inputboards=[5.6, 5.7, 6.8, 6.9, 6.10]
current_layer=[5.5]
buffer=[4.4]
scrap=2
`")

t2-2["`invalid
`"]

t2-3["`
inputboards=[5.5, 5.6, 5.7, 6.8, 6.9, 6.10]
current_layer=[4.4]
buffer=[]
scrap=5
`"]

t2 -->|add to layer| t2-1
t2 -->|put into buffer| t2-2
t2 -. take from buffer - redundant solution .-> t2-3


t1-1-1("`inputboards=[5.7, 6.8, 6.9, 6.10]
current_layer=[4.4, 5.5, 5.6]
buffer=[]
scrap=8
`")

t1-1-2("`inputboards=[5.7, 6.8, 6.9, 6.10]
current_layer=[4.4, 5.5]
buffer=[5.6]
scrap=8
`")

t1-1-3("`invalid
`")


t1-1 -->|add to layer| t1-1-1
t1-1 -->|put into buffer| t1-1-2
t1-1 -->|take from buffer| t1-1-3

t1-2-1["`inputboards=[5.7, 6.8, 6.9, 6.10]
current_layer=[4.4, 5.6]
buffer=[5.5]
scrap=9
`"]

t1-2-2["`invalid
`"]

t1-2-3["`inputboards=[5.6, 5.7, 6.8, 6.9, 6.10]
current_layer=[4.4, 5.5]
buffer=[5.5]
scrap=8
`"]

t1-2 -->|add to layer| t1-2-1
t1-2 -->|put into buffer| t1-2-2
t1-2 -. take from buffer - redundant solution .-> t1-2-3

t2-1-1("`inputboards=[5.6, 5.7, 6.8, 6.9, 6.10]
current_layer=[5.5, 5.6]
buffer=[4.4]
scrap=4
`")

t2-1-2("`invalid
`")

t2-1-3("`inputboards=[5.6, 5.7, 6.8, 6.9, 6.10]
current_layer=[5.5, 4.4]
buffer=[]
scrap=2
`")

t2-1 -->|add to layer| t2-1-1
t2-1 -->|put into buffer| t2-1-2
t2-1 -->|take from buffer| t2-1-3


t1-1-1-1("`inputboards=[6.8, 6.9, 6.10]
current_layer=[4.4, 5.5, 5.6, 5.7]
buffer=[]
scrap=15
`")

t1-1-1-2("`inputboards=[6.8, 6.9, 6.10]
current_layer=[4.4, 5.5, 5.6]
buffer=[5.7]
scrap=8
`")

t1-1-1-3("`invalid
`")

t1-1-1 -->|add to layer| t1-1-1-1
t1-1-1 -->|put into buffer| t1-1-1-2
t1-1-1 -. take from buffer .-> t1-1-1-3


```
